pages = [
  "/work/arcadia",
  "/work/dosomething",
  "/work/warren-2020",
  "/work/markey-2020",
  "/work/neighbor-network",
  "/work/when-we-all-vote",
  "/work/all-in",
  "/work/vote-from-home",
  "/work/data-for-progress",
  "/work/georgia-2020",
  "/work/invest-in-america",
  "/work/fuller-project"
]