title = "Georgia 2020 Senate Runoffs"
subtitle = "Designed & built social & relational organizing tools for the Georgia senate runoffs."

template = "content"

[sections]

[sections.toolkit1]
type = "panel"
imageSrc = "/assets/portfolio/ossoff-media.png"
imageAlt = "Screenshot of a web page offering downloadable graphics for social media"
markdown = """\
I worked as a freelancer to help the Jon Ossoff campaign create a website dedicated to hosting "toolkits" that the campaign could distribute to relational organizers.

The toolkits had a dedicated cms for campaign staff, and a light taxonomy system to help categorize all of the pages.

The pages were designed and built by me in the weeks leading up to the runoff election.

Read more, [How we built a relational network of 160k voters in less than a month](https://medium.com/@davisleonard/how-we-built-a-relational-network-of-160k-voters-in-less-than-a-month-92262926fdb0)
"""

[sections.toolkit2]
type = "cover"
coverSrc = "/assets/portfolio/ossoff-relational.png"
coverAlt = "Screenshot of a web page describing the concept of relational organizing for a campaign"

[sections.warnockScreenshot]
type = "cover"
coverSrc = "/assets/portfolio/warnock.jpg"
coverAlt = "Screenshot of a web app that lets you upload a photo and customize it to match the campaign branding"

[sections.warnock]
type = "markdown"
markdown = """\
I worked as a freelancer to help the Warnock campaign create a simple web application which allowed supporters to create custom social media graphics that they could then use to promote the campaign.

This web app was designed and built by me in the weeks leading up to the runoff election.
"""