title = "Invest In America"
subtitle = "Created a rapid response calculator to help an advocacy group communicate why a larger stimulus check was necessary."

template = "content"

[sections]

[sections.hero]
type = "cover"
coverSrc = "/assets/portfolio/investinamerica.png"
coverAlt = "List of possible buttons describing ways to spend a government stimulus check, with Senator McConnell trolling the user"

[sections.summary]
type = "markdown"
markdown = """\
I worked with [Invest in America](https://twitter.com/InvestNowUSA) to create a rapid response calculator to advocate Americans recieve a higher stimulus check from the government during the pandemic.

I designed & built the calculator on a rapid response timeline.
"""